<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #333; margin: 0; padding: 20px; }
    h1 { font-size: 20px; color: #1a56db; margin-bottom: 4px; }
    .header { border-bottom: 2px solid #1a56db; margin-bottom: 16px; padding-bottom: 8px; }
    .meta { font-size: 11px; color: #666; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { padding: 7px 10px; border: 1px solid #ddd; text-align: left; }
    th { background: #f0f4ff; font-weight: bold; }
    .total-row td { font-weight: bold; background: #f8f9fa; }
    .section-title { font-weight: bold; color: #1a56db; margin: 14px 0 4px; font-size: 13px; }
    .footer { margin-top: 24px; font-size: 10px; color: #888; border-top: 1px solid #eee; padding-top: 8px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; background: #e0f2fe; color: #0369a1; }
</style>
</head>
<body>

<div class="header">
    <h1>Technician World — Quotation</h1>
    <div class="meta">
        Reference: <strong>{{ $serviceRequest->request_id }}</strong> &nbsp;|&nbsp;
        Date: <strong>{{ now()->format('d M Y') }}</strong> &nbsp;|&nbsp;
        <span class="badge">{{ ucfirst(str_replace('_', ' ', $serviceRequest->rfq_status ?? 'quoted')) }}</span>
    </div>
</div>

<div>
    <strong>Client:</strong> {{ $serviceRequest->user->name ?? 'N/A' }}<br>
    <strong>Service:</strong> {{ $serviceRequest->serviceCategory->name ?? 'General Service' }}<br>
    <strong>Location:</strong> {{ $serviceRequest->location ?? 'N/A' }}
</div>

@if(!empty($materials))
<div class="section-title">Materials</div>
<table>
    <thead>
        <tr><th>Item</th><th>Qty</th><th>Unit Price (KES)</th><th>Total (KES)</th></tr>
    </thead>
    <tbody>
        @foreach($materials as $m)
        <tr>
            <td>{{ $m['name'] ?? 'Item' }}</td>
            <td>{{ $m['quantity'] ?? 1 }}</td>
            <td>{{ number_format($m['unit_price'] ?? 0, 2) }}</td>
            <td>{{ number_format(($m['quantity'] ?? 1) * ($m['unit_price'] ?? 0), 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="section-title">Cost Summary</div>
<table>
    <tbody>
        @if($laborCost > 0)
        <tr><td>Labour Cost</td><td>KES {{ number_format($laborCost, 2) }}</td></tr>
        @endif
        @if(!empty($materials))
        <tr><td>Materials</td><td>KES {{ number_format(collect($materials)->sum(fn($m) => ($m['quantity'] ?? 1) * ($m['unit_price'] ?? 0)), 2) }}</td></tr>
        @endif
        @if($transportCost > 0)
        <tr><td>Transport</td><td>KES {{ number_format($transportCost, 2) }}</td></tr>
        @endif
        <tr class="total-row"><td>Total</td><td>KES {{ number_format($totalAmount, 2) }}</td></tr>
        @if($downPayment > 0)
        <tr><td>Down Payment Required</td><td>KES {{ number_format($downPayment, 2) }}</td></tr>
        @endif
    </tbody>
</table>

@if(!empty($milestones) && count($milestones) > 0)
<div class="section-title">Billing Schedule</div>
<table>
    <thead>
        <tr><th>Milestone</th><th>At Progress %</th><th>Amount (KES)</th></tr>
    </thead>
    <tbody>
        @foreach($milestones as $ms)
        <tr>
            <td>{{ $ms->notes ?? 'Milestone' }}</td>
            <td>{{ $ms->progress_step }}%</td>
            <td>{{ number_format($ms->amount, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@if($notes)
<div class="section-title">Notes</div>
<p>{{ $notes }}</p>
@endif

<div class="section-title">Payment Options</div>
<table>
    <tbody>
        @if(!empty($mpesaPaybill))
        <tr>
            <th style="width:35%;">M-Pesa Paybill</th>
            <td>{{ $mpesaPaybill }} &nbsp; · &nbsp; Account: <strong>{{ $serviceRequest->request_id }}</strong></td>
        </tr>
        @endif
        @if(!empty($bank['name']))
        <tr>
            <th>Bank</th>
            <td>{{ $bank['name'] }}{{ !empty($bank['branch']) ? ' — ' . $bank['branch'] : '' }}</td>
        </tr>
        <tr>
            <th>Account Name</th>
            <td>{{ $bank['account_name'] }}</td>
        </tr>
        <tr>
            <th>Account Number</th>
            <td>{{ $bank['account_number'] }}</td>
        </tr>
        @if(!empty($bank['swift_code']))
        <tr>
            <th>SWIFT</th>
            <td>{{ $bank['swift_code'] }}</td>
        </tr>
        @endif
        @endif
    </tbody>
</table>

<div class="footer">
    This quotation was generated by Technician World. Valid for 30 days from issue date.
    For queries contact us via the portal or email info@technicianworld.co.ke
</div>

</body>
</html>
